// lib/services/language_service.dart
import 'package:flutter/material.dart';

class LanguageService extends ChangeNotifier {
  bool _isEnglish = false;

  bool get isEnglish => _isEnglish;

  void toggleLanguage() {
    _isEnglish = !_isEnglish;
    notifyListeners();
  }

  void setLanguage(bool isEnglish) {
    _isEnglish = isEnglish;
    notifyListeners();
  }

  // 获取当前语言的文本
  Map<String, String> get currentLanguage => _isEnglish ? _enText : _zhText;

  // 中文文本
  final Map<String, String> _zhText = {
    // 通用
    'appTitle': '逍遥游',
    'cancel': '取消',
    'confirm': '确认',
    'save': '保存',
    'delete': '删除',
    'edit': '编辑',
    'share': '分享',
    'like': '点赞',
    'comment': '评论',
    'favorite': '收藏',
    'loading': '加载中...',
    'noData': '暂无数据',
    'search': '搜索',
    'filter': '筛选',
    'all': '全部',
    
    // 主页
    'aiTravelPlanning': 'AI智能旅行规划',
    'startYourJourney': '开启您的阳光之旅',
    'customizeYourTrip': '定制您的专属旅程',
    'days': '天数',
    'budget': '预算（元）',
    'travelPurpose': '旅行目的',
    'tellAI': '告诉AI你的想法',
    'exampleText': '例如：我想去武汉玩3天，预算3000...',
    'generatePlan': '生成AI旅行规划',
    'quickBook': '一键购票',
    'coreFeatures': '常用服务',
    'hotelBooking': '酒店预订',
    'travelLocation': '旅游定位',
    'specialFood': '特色美食',
    'intangibleCulture': '非遗文化',
    'community': '逍遥社区',
    'photoWall': '照片墙',
    'reviews': '大众点评',
    'moreFeatures': '更多功能',
    'smartMap': '智能地图',
    'moreAttractions': '更多景区',
    'vipRecharge': 'VIP充值',
    
    // 文化探索
    'culturalExploration': '文化探索',
    'leisureVacation': '休闲度假',
    'foodTour': '美食之旅',
    'familyTrip': '家庭出游',
    'adventure': '冒险探索',
    
    // 登录页
    'welcome': '欢迎使用',
    'login': '登录',
    'register': '注册',
    'username': '用户名',
    'password': '密码',
    'confirmPassword': '确认密码',
    'email': '邮箱',
    'phone': '手机号',
    'verificationCode': '验证码',
    'getCode': '获取验证码',
    'forgotPassword': '忘记密码？',
    'agreeTerms': '我已阅读并同意',
    'userAgreement': '用户协议',
    'privacyPolicy': '隐私政策',
    'otherLoginMethods': '其他登录方式',
    'wechatLogin': '微信登录',
    'qqLogin': 'QQ登录',
    'emailLogin': '邮箱登录',
    'loginSuccess': '登录成功',
    'registerSuccess': '注册成功，请登录',
    'loginFailed': '登录失败',
    'registerFailed': '注册失败',
    'fillAllFields': '请填写完整信息',
    'passwordMismatch': '两次密码不一致',
    
    // 个人中心
    'profile': '个人中心',
    'follow': '关注',
    'followers': '粉丝',
    'messages': '私信',
    'vipMember': 'VIP会员',
    'validUntil': '有效期至',
    'openVip': '立即开通',
    'alreadyVip': '已开通',
    'browseHistory': '浏览记录',
    'myFavorites': '我的收藏',
    'searchHistory': '历史询问',
    'watchLater': '稍后再看',
    'interested': '可能感兴趣的地方',
    'settings': '设置',
    'help': '帮助与反馈',
    'editProfile': '编辑资料',
    'changeAvatar': '更换头像',
    'changeNickname': '修改昵称',
    'saveChanges': '保存修改',
    
    // VIP充值
    'vipRechargeTitle': 'VIP会员充值',
    'vipBenefits': '开通VIP会员，享受更多权益',
    'monthlyVip': '月度会员',
    'quarterlyVip': '季度会员',
    'yearlyVip': '年度会员',
    'days': '天',
    'originalPrice': '原价',
    'hotRecommend': '热门推荐',
    'paymentMethod': '支付方式',
    'wechatPay': '微信支付',
    'alipay': '支付宝',
    'cardPay': '银行卡',
    'confirmPayment': '确认支付',
    'paymentSuccess': '支付成功',
    'paymentFailed': '支付失败',
    
    // 酒店页面
    'hotelTitle': '酒店预订',
    'checkIn': '入住日期',
    'checkOut': '离店日期',
    'guests': '入住人数',
    'rooms': '房间数',
    'searchHotel': '搜索酒店',
    'hotelType': '酒店类型',
    'priceRange': '价格范围',
    'rating': '评分',
    'facilities': '设施服务',
    'bookNow': '立即预订',
    'hotelDetail': '酒店详情',
    'roomType': '房型',
    'breakfast': '早餐',
    'wifi': 'Wi-Fi',
    'parking': '停车场',
    'swimmingPool': '游泳池',
    'gym': '健身房',
    
    // 美食页面
    'foodTitle': '特色美食',
    'foodCategory': '美食分类',
    'popularFood': '人气美食',
    'nearbyFood': '附近美食',
    'foodDetail': '美食详情',
    'restaurant': '餐厅',
    'address': '地址',
    'businessHours': '营业时间',
    'phoneNumber': '联系电话',
    'averagePrice': '人均消费',
    'recommendedDishes': '推荐菜品',
    'userReviews': '用户评价',
    
    // 非遗文化页面
    'cultureTitle': '非遗文化',
    'cultureCategory': '非遗分类',
    'region': '地区',
    'cultureDetail': '非遗详情',
    'inheritor': '传承人',
    'history': '历史渊源',
    'features': '技艺特点',
    'protection': '保护现状',
    'experience': '体验活动',
    'bookExperience': '预约体验',
    
    // 更多景区页面
    'attractionsTitle': '更多景区',
    'currentLocation': '当前位置',
    'changeLocation': '更换',
    'searchAttractions': '搜索景区',
    'attractionType': '景区类型',
    'distance': '距离',
    'price': '价格',
    'openTime': '开放时间',
    'attractionDetail': '景区详情',
    'viewOnMap': '查看地图',
    'addToFavorites': '加入收藏',
    'writeReview': '写点评',
    
    // 照片墙页面
    'photoWallTitle': '旅行日记',
    'recommended': '推荐',
    'latest': '最新',
    'following': '关注',
    'postTitle': '标题',
    'postContent': '内容',
    'addPhoto': '添加图片',
    'addVideo': '添加视频',
    'publish': '发布',
    'createPost': '创建新帖子',
    
    // 点评页面
    'reviewsTitle': '大众点评',
    'allReviews': '全部',
    'food': '美食',
    'hotel': '酒店',
    'attraction': '景点',
    'writeComment': '写评论',
    'send': '发送',
    'reply': '回复',
    'report': '举报',
    
    // 地图页面
    'mapTitle': '智能地图',
    'chooseMap': '选择地图',
    'amap': '高德地图',
    'qqMap': '腾讯地图',
    'baiduMap': '百度地图',
    'currentLocation': '当前位置',
    'routePlan': '路线规划',
    'startPoint': '起点',
    'endPoint': '终点',
    'startNavigation': '开始导航',
    
    // 底部文案
    'footerQuote': '北冥有鱼，其名为鲲。鲲之大，不知其几千里也。化而为鸟，其名为鹏。',
    'copyright': '© 2026 逍遥游',
    
    // AI生成相关
    'aiGenerating': '鲲鹏展翅，书中寻路...',
    'aiPlanGenerated': '扶摇直上九万里',
    'aiPlanSubtitle': '您的行程已规划',
    'savePlan': '珍藏此卷',
    'day': '第',
    'daySuffix': '日',
  };

  // 英文文本
  final Map<String, String> _enText = {
    // General
    'appTitle': 'Carefree Journey',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'save': 'Save',
    'delete': 'Delete',
    'edit': 'Edit',
    'share': 'Share',
    'like': 'Like',
    'comment': 'Comment',
    'favorite': 'Favorite',
    'loading': 'Loading...',
    'noData': 'No Data',
    'search': 'Search',
    'filter': 'Filter',
    'all': 'All',
    
    // Home Page
    'aiTravelPlanning': 'AI Travel Planning',
    'startYourJourney': 'Start Your Journey',
    'customizeYourTrip': 'Customize Your Trip',
    'days': 'Days',
    'budget': 'Budget (¥)',
    'travelPurpose': 'Purpose',
    'tellAI': 'Tell AI Your Thoughts',
    'exampleText': 'e.g., I want to visit Wuhan for 3 days, budget 3000...',
    'generatePlan': 'Generate AI Plan',
    'quickBook': 'Quick Book',
    'coreFeatures': 'Core Services',
    'hotelBooking': 'Hotel',
    'travelLocation': 'Location',
    'specialFood': 'Food',
    'intangibleCulture': 'Culture',
    'community': 'Community',
    'photoWall': 'Photo Wall',
    'reviews': 'Reviews',
    'moreFeatures': 'More Features',
    'smartMap': 'Smart Map',
    'moreAttractions': 'Attractions',
    'vipRecharge': 'VIP',
    
    // Travel Purposes
    'culturalExploration': 'Cultural',
    'leisureVacation': 'Leisure',
    'foodTour': 'Food Tour',
    'familyTrip': 'Family',
    'adventure': 'Adventure',
    
    // Login Page
    'welcome': 'Welcome',
    'login': 'Login',
    'register': 'Register',
    'username': 'Username',
    'password': 'Password',
    'confirmPassword': 'Confirm Password',
    'email': 'Email',
    'phone': 'Phone',
    'verificationCode': 'Code',
    'getCode': 'Get Code',
    'forgotPassword': 'Forgot Password?',
    'agreeTerms': 'I agree to the',
    'userAgreement': 'User Agreement',
    'privacyPolicy': 'Privacy Policy',
    'otherLoginMethods': 'Other Login Methods',
    'wechatLogin': 'WeChat',
    'qqLogin': 'QQ',
    'emailLogin': 'Email',
    'loginSuccess': 'Login Successful',
    'registerSuccess': 'Registration Successful, Please Login',
    'loginFailed': 'Login Failed',
    'registerFailed': 'Registration Failed',
    'fillAllFields': 'Please Fill All Fields',
    'passwordMismatch': 'Passwords Do Not Match',
    
    // Profile Page
    'profile': 'Profile',
    'follow': 'Following',
    'followers': 'Followers',
    'messages': 'Messages',
    'vipMember': 'VIP Member',
    'validUntil': 'Valid Until',
    'openVip': 'Open VIP',
    'alreadyVip': 'Active',
    'browseHistory': 'History',
    'myFavorites': 'Favorites',
    'searchHistory': 'Searches',
    'watchLater': 'Watch Later',
    'interested': 'Interested',
    'settings': 'Settings',
    'help': 'Help',
    'editProfile': 'Edit Profile',
    'changeAvatar': 'Change Avatar',
    'changeNickname': 'Change Nickname',
    'saveChanges': 'Save Changes',
    
    // VIP Recharge
    'vipRechargeTitle': 'VIP Recharge',
    'vipBenefits': 'Upgrade to VIP for More Benefits',
    'monthlyVip': 'Monthly VIP',
    'quarterlyVip': 'Quarterly VIP',
    'yearlyVip': 'Yearly VIP',
    'days': 'Days',
    'originalPrice': 'Original',
    'hotRecommend': 'Hot',
    'paymentMethod': 'Payment Method',
    'wechatPay': 'WeChat Pay',
    'alipay': 'Alipay',
    'cardPay': 'Bank Card',
    'confirmPayment': 'Confirm Payment',
    'paymentSuccess': 'Payment Successful',
    'paymentFailed': 'Payment Failed',
    
    // Hotel Page
    'hotelTitle': 'Hotel Booking',
    'checkIn': 'Check-in',
    'checkOut': 'Check-out',
    'guests': 'Guests',
    'rooms': 'Rooms',
    'searchHotel': 'Search Hotel',
    'hotelType': 'Hotel Type',
    'priceRange': 'Price Range',
    'rating': 'Rating',
    'facilities': 'Facilities',
    'bookNow': 'Book Now',
    'hotelDetail': 'Hotel Details',
    'roomType': 'Room Type',
    'breakfast': 'Breakfast',
    'wifi': 'Wi-Fi',
    'parking': 'Parking',
    'swimmingPool': 'Pool',
    'gym': 'Gym',
    
    // Food Page
    'foodTitle': 'Local Food',
    'foodCategory': 'Category',
    'popularFood': 'Popular',
    'nearbyFood': 'Nearby',
    'foodDetail': 'Food Details',
    'restaurant': 'Restaurant',
    'address': 'Address',
    'businessHours': 'Hours',
    'phoneNumber': 'Phone',
    'averagePrice': 'Avg. Price',
    'recommendedDishes': 'Recommended',
    'userReviews': 'Reviews',
    
    // Culture Page
    'cultureTitle': 'Intangible Culture',
    'cultureCategory': 'Category',
    'region': 'Region',
    'cultureDetail': 'Details',
    'inheritor': 'Inheritor',
    'history': 'History',
    'features': 'Features',
    'protection': 'Protection',
    'experience': 'Experience',
    'bookExperience': 'Book Experience',
    
    // Attractions Page
    'attractionsTitle': 'Attractions',
    'currentLocation': 'Current Location',
    'changeLocation': 'Change',
    'searchAttractions': 'Search Attractions',
    'attractionType': 'Type',
    'distance': 'Distance',
    'price': 'Price',
    'openTime': 'Open Time',
    'attractionDetail': 'Details',
    'viewOnMap': 'View on Map',
    'addToFavorites': 'Add to Favorites',
    'writeReview': 'Write Review',
    
    // Photo Wall Page
    'photoWallTitle': 'Travel Diary',
    'recommended': 'Recommended',
    'latest': 'Latest',
    'following': 'Following',
    'postTitle': 'Title',
    'postContent': 'Content',
    'addPhoto': 'Add Photo',
    'addVideo': 'Add Video',
    'publish': 'Publish',
    'createPost': 'Create Post',
    
    // Reviews Page
    'reviewsTitle': 'Reviews',
    'allReviews': 'All',
    'food': 'Food',
    'hotel': 'Hotel',
    'attraction': 'Attraction',
    'writeComment': 'Write Comment',
    'send': 'Send',
    'reply': 'Reply',
    'report': 'Report',
    
    // Map Page
    'mapTitle': 'Smart Map',
    'chooseMap': 'Choose Map',
    'amap': 'Amap',
    'qqMap': 'QQ Map',
    'baiduMap': 'Baidu Map',
    'currentLocation': 'Current Location',
    'routePlan': 'Route Plan',
    'startPoint': 'Start',
    'endPoint': 'End',
    'startNavigation': 'Start',
    
    // Footer
    'footerQuote': 'In the northern darkness, there is a fish named Kun...',
    'copyright': '© 2026 Carefree Journey',
    
    // AI Generation
    'aiGenerating': 'Kun spreads wings, seeking path in books...',
    'aiPlanGenerated': 'Soaring ninety thousand miles',
    'aiPlanSubtitle': 'Your journey is planned',
    'savePlan': 'Save This Scroll',
    'day': 'Day ',
    'daySuffix': '',
  };
}