name: travel_app
description: 逍遥游 - AI智能旅行规划
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状态管理
  provider: ^6.1.1
  
  # 地图跳转
  url_launcher: ^6.2.1
  
  # 视频播放
  video_player: ^2.8.1
  
  # WebView
  webview_flutter: ^4.4.2
  
  # 网络请求
  http: ^1.1.0
  
  # 本地存储
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/homebackground.jpg
    # - assets/images/cloud_pattern.png
    # - assets/images/paper_texture.png
    # - assets/images/tree_pattern.png
    # - assets/images/hotelbackground.jpg
    - assets/gifs/kunpeng.gif